#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
blue=`tput setaf 4`
magenta=`tput setaf 5`
cyan=`tput setaf 6`
reset=`tput sgr0`

printf "\n${magenta}Deleting previous build files...${reset}\n"
rm -rf Output_Files
mkdir ./Output_Files

printf "\n${magenta}Assembling individual PRG banks...${reset}\n\n"
cd Source_Files

../Ophis/ophis Header.asm ../output_files/Header.bin
../Ophis/ophis Bank00.asm ../output_files/Bank00.bin
../Ophis/ophis Bank01.asm ../output_files/Bank01.bin
../Ophis/ophis Bank02.asm ../output_files/Bank02.bin
../Ophis/ophis Bank03.asm ../output_files/Bank03.bin
cd ..

printf "\n${magenta}Calculating checksums of individual PRG banks...${reset}\n\n"
printf -- "${yellow}--------------------PRG Bank 00--------------------${reset}\n"
out00=($(md5sum output_files/Bank00.bin))
org00="4494467c3c7f3401a5ea25947814b8bd"
printf "Assembled md5sum = $out00\n"
printf "Original  md5sum = $org00\n"
if [ "$out00" = "$org00" ]; then
    printf "${green}Pass${reset}\n\n"
else
    printf "${red}Fail${reset}\n\n"
fi

printf -- "${yellow}--------------------PRG Bank 01--------------------${reset}\n"
out01=($(md5sum output_files/Bank01.bin))
org01="e34c39bfb3069bc6c563b0e614b22a49"
printf "Assembled md5sum = $out01\n"
printf "Original  md5sum = $org01\n"
if [ "$out01" = "$org01" ]; then
    printf "${green}Pass${reset}\n\n"
else
    printf "${red}Fail${reset}\n\n"
fi

printf -- "${yellow}--------------------PRG Bank 02--------------------${reset}\n"
out02=($(md5sum output_files/Bank02.bin))
org02="0135d12602c3efb5728a0f220ae916fd"
printf "Assembled md5sum = $out02\n"
printf "Original  md5sum = $org02\n"
if [ "$out02" = "$org02" ]; then
    printf "${green}Pass${reset}\n\n"
else
    printf "${red}Fail${reset}\n\n"
fi

printf -- "${yellow}--------------------PRG Bank 03--------------------${reset}\n"
out03=($(md5sum output_files/Bank03.bin))
org03="aae638b52ffc7a720a63d6ef1700a2b3"
printf "Assembled md5sum = $out03\n"
printf "Original  md5sum = $org03\n"
if [ "$out03" = "$org03" ]; then
    printf "${green}Pass${reset}\n\n"
else
    printf "${red}Fail${reset}\n\n"
fi

#printf "${magenta}Combining Assembled banks into a ROM...${reset}\n"
#cat output_files/Header.bin \
#	output_files/Bank00.bin \
#	output_files/Bank01.bin \
#	output_files/Bank02.bin \
#	output_files/Bank03.bin \
#	original_files/CHR_ROM.bin \
#	> assembled_dragon_warrior.nes
